#!/usr/bin/env python3
# StimGen 2 -- SPDX-License-Identifier: MIT
#
# Copyright (c) 2026 Michele Giugliano
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""
build.py -- regenerate the parts of skill/stimgen2/ that are derived from sg.

    python3 skill/build.py           # rewrite them
    python3 skill/build.py --check   # exit 1 if any of them is out of date

Derived parts: references/sg-help.md (the built-in help of sg, verbatim) and
scripts/sgconvert.py (a copy of tools/sgconvert.py). Everything else in the
skill is written by hand.
"""
import os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SKILL = os.path.join(HERE, "stimgen2")
SG = os.path.join(ROOT, "src", "sg")

TOPICS = ["syntax", "generators", "maps", "units", "stimulus", "noise", "protocol", "output"]
GENERATORS = ["dc", "ramp", "relax", "sine", "square", "saw", "triangle", "chirp", "biexp",
              "alpha", "file", "pulses", "ou", "wnoise", "unoise", "cnoise"]


def sg(*args):
    return subprocess.run([SG, *args], capture_output=True, text=True, check=True).stdout.rstrip()


def help_md():
    out = ["# sg built-in help (verbatim)", "",
           "Generated by `skill/build.py` from `sg " + sg("version").split()[1]
           + "`. This file is the ground truth for syntax and parameters;",
           "if anything else in the skill disagrees with it, trust this file (or `sg help` itself).", ""]
    out += ["## sg --help", "", "```", sg("--help"), "```", ""]
    for t in TOPICS:
        out += [f"## sg help {t}", "", "```", sg("help", t), "```", ""]
    out += ["## Generators, one by one", ""]
    for g in GENERATORS:
        out += [f"### {g}", "", "```", sg("help", g), "```", ""]
    out += ["## sg examples", "", "```", sg("examples"), "```", ""]
    return "\n".join(out)


def main():
    check = "--check" in sys.argv
    if not os.path.exists(SG):
        subprocess.run(["make", "-C", os.path.join(ROOT, "src")], check=True)
    files = {
        os.path.join(SKILL, "references", "sg-help.md"): help_md(),
        os.path.join(SKILL, "scripts", "sgconvert.py"): open(os.path.join(ROOT, "tools", "sgconvert.py")).read(),
    }
    stale = []
    for path, text in files.items():
        old = open(path).read() if os.path.exists(path) else None
        if old != text:
            stale.append(os.path.relpath(path, ROOT))
            if not check:
                with open(path, "w") as f:
                    f.write(text)
    if check:
        if stale:
            sys.exit("out of date (run python3 skill/build.py): " + ", ".join(stale))
        print("skill: derived files up to date")
    else:
        print("skill: wrote " + (", ".join(stale) if stale else "nothing (up to date)"))


if __name__ == "__main__":
    main()
